const SUPABASE_URL='https://oxirewjzmnfnbwiugoac.supabase.co';
const SUPABASE_KEY='sb_publishable_gkc-Cjh2ykNYvlf5JRf3NQ_UU2s73jC';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
const WORKSPACE_CACHE_KEY='cecilia_workspace_cache_v2';
const BACKUP_INTERVAL=6*60*60*1000;
const PULL_INTERVAL=5*60*1000;
const SYNC_DEBOUNCE=3000;

let state=emptyState();
let currentUser=null;
let workspaceId=null;
let workspaceRole=null;
let currentClientId=null;
let editingClientId=null;
let editingDebtId=null;
let editingPaymentId=null;
let deferredPrompt=null;
let syncTimer=null;
let syncing=false;
let lastSyncAttempt=0;

const el=id=>document.getElementById(id);
function emptyState(){return {clients:[],debts:[],payments:[]}}
function localKey(){return workspaceId?`cecilia_state_v2_${workspaceId}`:'cecilia_state_v2_unassigned'}
function queueKey(){return workspaceId?`cecilia_mutations_v2_${workspaceId}`:'cecilia_mutations_v2_unassigned'}
function pullKey(){return workspaceId?`cecilia_last_pull_v2_${workspaceId}`:'cecilia_last_pull_v2_unassigned'}
function backupKey(){return workspaceId?`cecilia_last_backup_v2_${workspaceId}`:'cecilia_last_backup_v2_unassigned'}
function id(){if(crypto.randomUUID)return crypto.randomUUID();const a=crypto.getRandomValues(new Uint8Array(16));a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;return [...a].map((b,i)=>([4,6,8,10].includes(i)?'-':'')+b.toString(16).padStart(2,'0')).join('')}
function nowIso(){return new Date().toISOString()}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function money(v){return 'Gs. '+Math.round(Number(v)||0).toLocaleString('es-PY')}
function fmtDate(s){if(!s)return'-';const [y,m,d]=String(s).split('-');return y&&m&&d?`${d}/${m}/${y}`:s}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function active(arr){return arr.filter(x=>!x.deletedAt)}
function clientById(cid){return state.clients.find(c=>c.id===cid&&!c.deletedAt)}

function normalizeState(data){
  const safe=data&&typeof data==='object'?data:emptyState();
  const stamp=nowIso();
  return {
    clients:Array.isArray(safe.clients)?safe.clients.map(c=>({id:c.id||id(),name:c.name||'',doc:c.doc||'',phone:c.phone||'',address:c.address||'',notes:c.notes||'',createdAt:Number(c.createdAt)||Date.now(),updatedAt:c.updatedAt||stamp,deletedAt:c.deletedAt||''})):[],
    debts:Array.isArray(safe.debts)?safe.debts.map(d=>({id:d.id||id(),clientId:d.clientId||'',concept:d.concept||'',amount:Number(d.amount)||0,date:d.date||today(),due:d.due||'',createdAt:Number(d.createdAt)||Date.now(),updatedAt:d.updatedAt||stamp,deletedAt:d.deletedAt||''})):[],
    payments:Array.isArray(safe.payments)?safe.payments.map(p=>({id:p.id||id(),clientId:p.clientId||'',amount:Number(p.amount)||0,date:p.date||today(),method:p.method||'Efectivo',ref:p.ref||'',createdAt:Number(p.createdAt)||Date.now(),updatedAt:p.updatedAt||stamp,deletedAt:p.deletedAt||''})):[]
  };
}
function loadLocal(){try{state=normalizeState(JSON.parse(localStorage.getItem(localKey())||'null'))}catch{state=emptyState()}}
function persistLocal(){if(workspaceId)localStorage.setItem(localKey(),JSON.stringify(state))}
function readQueue(){try{const q=JSON.parse(localStorage.getItem(queueKey())||'[]');return Array.isArray(q)?q:[]}catch{return []}}
function writeQueue(q){if(!workspaceId)return;if(q.length)localStorage.setItem(queueKey(),JSON.stringify(q));else localStorage.removeItem(queueKey())}
function queueMutation(table,recordId){const q=readQueue();if(!q.some(x=>x.table===table&&x.id===recordId))q.push({table,id:recordId});writeQueue(q);updateConnectivityUi()}
function removeQueued(items){const keys=new Set(items.map(x=>`${x.table}:${x.id}`));writeQueue(readQueue().filter(x=>!keys.has(`${x.table}:${x.id}`)))}
function isDirty(){return readQueue().length>0}

function totalDebt(cid){return active(state.debts).filter(d=>!cid||d.clientId===cid).reduce((s,d)=>s+Number(d.amount||0),0)}
function totalPaid(cid){return active(state.payments).filter(p=>!cid||p.clientId===cid).reduce((s,p)=>s+Number(p.amount||0),0)}
function balance(cid){return Math.max(0,totalDebt(cid)-totalPaid(cid))}
function debtRemaining(debt){const arr=active(state.debts).filter(d=>d.clientId===debt.clientId).sort((a,b)=>String(a.date).localeCompare(String(b.date))||(a.createdAt||0)-(b.createdAt||0));let paid=totalPaid(debt.clientId);for(const d of arr){const used=Math.min(Number(d.amount||0),Math.max(0,paid));const rem=Number(d.amount||0)-used;paid-=used;if(d.id===debt.id)return Math.max(0,rem)}return Number(debt.amount||0)}

function setCloudStatus(status,message){if(el('dataBadge'))el('dataBadge').textContent=status;if(el('sidebarStorage'))el('sidebarStorage').textContent=message;if(el('cloudStatusText'))el('cloudStatusText').textContent=message}
function updateConnectivityUi(){
  if(!navigator.onLine){setCloudStatus(isDirty()?'Offline · pendiente':'Offline',isDirty()?'Cambios guardados en este equipo. Se sincronizarán al volver Internet.':'Datos disponibles en este equipo.');return}
  if(syncing){setCloudStatus('Sincronizando...','Actualizando la copia segura en la nube.');return}
  if(currentUser&&workspaceId){setCloudStatus(isDirty()?'Pendiente':'Sincronizado',isDirty()?'Cambio guardado localmente; la nube se actualizará automáticamente.':'Datos sincronizados correctamente con la nube.');return}
  setCloudStatus('Acceso requerido','Iniciá sesión para acceder a Cecilia Comercial.')
}
function lockApp(message='Iniciá sesión con una cuenta autorizada para acceder a Cecilia Comercial.'){
  const layout=document.querySelector('.layout');if(layout)layout.style.display='none';
  let gate=el('accessGate');
  if(!gate){gate=document.createElement('section');gate.id='accessGate';gate.style.cssText='min-height:calc(100vh - 82px);display:grid;place-items:center;padding:24px;background:#f7f4ed';gate.innerHTML=`<div style="max-width:520px;width:100%;background:#fff;border:1px solid #e5dcc5;border-radius:18px;padding:28px;box-shadow:0 18px 50px rgba(0,0,0,.08)"><span class="eyebrow">Acceso privado</span><h2 style="margin:6px 0 10px">Cecilia Comercial</h2><p id="accessGateText" style="color:#64748b;line-height:1.55;margin:0 0 20px"></p><button class="btn btn-primary" onclick="openAuthModal()">Iniciar sesión</button></div>`;document.querySelector('.topbar')?.insertAdjacentElement('afterend',gate)}
  const t=el('accessGateText');if(t)t.textContent=message;gate.style.display='grid';updateConnectivityUi();
}
function unlockApp(){const layout=document.querySelector('.layout');if(layout)layout.style.display='grid';const gate=el('accessGate');if(gate)gate.style.display='none';updateConnectivityUi()}
function updateAuthUi(){const signed=!!currentUser&&!!workspaceId;if(el('cloudBtn'))el('cloudBtn').textContent=signed?'Nube conectada':'Iniciar sesión';if(el('configCloudBtn'))el('configCloudBtn').classList.toggle('hidden',signed);if(el('restoreCloudBtn'))el('restoreCloudBtn').classList.toggle('hidden',!signed);if(el('signOutBtn'))el('signOutBtn').classList.toggle('hidden',!signed);updateConnectivityUi()}

function navSetup(){document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>goView(b.dataset.view)))}
function goView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const t=el(v);if(t)t.classList.add('active');renderAll()}

function renderDashboard(){const ym=today().slice(0,7);const payments=active(state.payments);const debts=active(state.debts);const clients=active(state.clients);const paidMonth=payments.filter(p=>String(p.date||'').startsWith(ym)).reduce((s,p)=>s+Number(p.amount||0),0);const overdue=debts.filter(d=>d.due&&d.due<today()).reduce((s,d)=>s+debtRemaining(d),0);el('kpiSaldo').textContent=money(balance());el('kpiMes').textContent=money(paidMonth);el('kpiVencida').textContent=money(overdue);el('kpiClientes').textContent=clients.filter(c=>balance(c.id)>0).length;const top=clients.map(c=>({c,b:balance(c.id)})).filter(x=>x.b>0).sort((a,b)=>b.b-a.b).slice(0,5);el('topClientes').innerHTML=top.length?top.map(x=>`<div class="list-row"><span>${esc(x.c.name)}</span><strong>${money(x.b)}</strong></div>`).join(''):'<div class="empty">Sin saldos pendientes.</div>';const last=[...payments].sort((a,b)=>String(b.date).localeCompare(String(a.date))||Number(b.createdAt||0)-Number(a.createdAt||0)).slice(0,5);el('ultimosPagos').innerHTML=last.length?last.map(p=>`<div class="list-row"><span>${esc(clientById(p.clientId)?.name||'Cliente')}</span><strong>${money(p.amount)}</strong></div>`).join(''):'<div class="empty">Aún no hay pagos registrados.</div>'}
function renderClients(){const q=(el('clientSearch')?.value||'').toLowerCase();const arr=active(state.clients).filter(c=>[c.name,c.doc,c.phone].join(' ').toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name));el('clientsTable').innerHTML=arr.length?arr.map(c=>`<tr><td><button class="client-link" onclick="showClient('${c.id}')">${esc(c.name)}</button></td><td>${esc(c.doc||'-')}</td><td>${esc(c.phone||'-')}</td><td><strong>${money(balance(c.id))}</strong></td><td><div class="row-actions"><button class="btn btn-secondary btn-small" onclick="showClient('${c.id}')">Ver</button><button class="btn btn-secondary btn-small" onclick="editClient('${c.id}')">Editar</button><button class="btn btn-danger btn-small" onclick="deleteClient('${c.id}')">Eliminar</button></div></td></tr>`).join(''):'<tr><td colspan="5" class="empty-row">No hay clientes registrados.</td></tr>'}
function renderDebts(){const arr=[...active(state.debts)].sort((a,b)=>String(b.date).localeCompare(String(a.date)));el('debtsTable').innerHTML=arr.length?arr.map(d=>{const rem=debtRemaining(d),overdue=d.due&&d.due<today()&&rem>0;const cls=rem<=0?'ok':overdue?'bad':'warn';const label=rem<=0?'Pagada':overdue?'Vencida':'Pendiente';return `<tr><td>${esc(clientById(d.clientId)?.name||'-')}</td><td>${esc(d.concept)}</td><td>${fmtDate(d.date)}</td><td>${d.due?fmtDate(d.due):'-'}</td><td>${money(d.amount)}</td><td><strong>${money(rem)}</strong></td><td><span class="status ${cls}">${label}</span></td><td><div class="row-actions"><button class="btn btn-secondary btn-small" onclick="editDebt('${d.id}')">Editar</button><button class="btn btn-danger btn-small" onclick="deleteDebt('${d.id}')">Eliminar</button></div></td></tr>`}).join(''):'<tr><td colspan="8" class="empty-row">No hay deudas registradas.</td></tr>'}
function renderPayments(){const arr=[...active(state.payments)].sort((a,b)=>String(b.date).localeCompare(String(a.date))||Number(b.createdAt||0)-Number(a.createdAt||0));el('paymentsTable').innerHTML=arr.length?arr.map(p=>`<tr><td>${fmtDate(p.date)}</td><td>${esc(clientById(p.clientId)?.name||'-')}</td><td><strong>${money(p.amount)}</strong></td><td>${esc(p.method)}</td><td>${esc(p.ref||'-')}</td><td><div class="row-actions"><button class="btn btn-secondary btn-small" onclick="editPayment('${p.id}')">Editar</button><button class="btn btn-danger btn-small" onclick="deletePayment('${p.id}')">Eliminar</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="empty-row">No hay pagos registrados.</td></tr>'}
function renderReports(){const clients=active(state.clients);el('repDeuda').textContent=money(totalDebt());el('repPagado').textContent=money(totalPaid());el('repSaldo').textContent=money(balance());const rows=clients.map(c=>({name:c.name,debt:totalDebt(c.id),paid:totalPaid(c.id),bal:balance(c.id)})).sort((a,b)=>b.bal-a.bal);el('reportClientBalances').innerHTML=rows.length?`<div class="table-wrap embedded"><table><thead><tr><th>Cliente</th><th>Deuda</th><th>Pagado</th><th>Saldo</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${money(r.debt)}</td><td>${money(r.paid)}</td><td><strong>${money(r.bal)}</strong></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sin datos para reportar.</div>'}
function populateClientSelects(){const ordered=[...active(state.clients)].sort((a,b)=>a.name.localeCompare(b.name));const opts='<option value="">Seleccionar...</option>'+ordered.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');el('dClient').innerHTML=opts;el('pClient').innerHTML=opts}
function renderClientDetail(){const c=clientById(currentClientId);if(!c){if(el('clientDetail')?.classList.contains('active'))goView('clientes');return}el('detailName').textContent=c.name;el('detailMeta').textContent=[c.doc,c.phone,c.address].filter(Boolean).join(' · ');el('detailDebt').textContent=money(totalDebt(c.id));el('detailPaid').textContent=money(totalPaid(c.id));el('detailBalance').textContent=money(balance(c.id));const mov=[...active(state.debts).filter(d=>d.clientId===c.id).map(d=>({date:d.date,createdAt:d.createdAt||0,type:'Deuda',detail:d.concept,cargo:Number(d.amount),abono:0})),...active(state.payments).filter(p=>p.clientId===c.id).map(p=>({date:p.date,createdAt:p.createdAt||0,type:'Pago',detail:p.method+(p.ref?' · '+p.ref:''),cargo:0,abono:Number(p.amount)}))].sort((a,b)=>String(a.date).localeCompare(String(b.date))||a.createdAt-b.createdAt);let running=0;el('detailLedger').innerHTML=mov.length?mov.map(m=>{running+=m.cargo-m.abono;return `<tr><td>${fmtDate(m.date)}</td><td>${m.type}</td><td>${esc(m.detail)}</td><td>${m.cargo?money(m.cargo):'-'}</td><td>${m.abono?money(m.abono):'-'}</td><td><strong>${money(Math.max(0,running))}</strong></td></tr>`}).join(''):'<tr><td colspan="6" class="empty-row">Este cliente todavía no tiene movimientos.</td></tr>'}
function renderAll(){if(!workspaceId)return;renderDashboard();renderClients();renderDebts();renderPayments();renderReports();populateClientSelects();if(el('clientDetail')?.classList.contains('active'))renderClientDetail();updateConnectivityUi()}
function showClient(cid){currentClientId=cid;goView('clientDetail')}

function saveRecord(table,record){record.updatedAt=nowIso();persistLocal();queueMutation(table,record.id);renderAll();scheduleCloudSync()}
function openClientModal(){editingClientId=null;el('clientForm').reset();el('clientModal').querySelector('.modal-head h3').textContent='Nuevo cliente';el('saveClientBtn').textContent='Guardar cliente';el('clientModal').showModal()}
function editClient(cid){const c=clientById(cid);if(!c)return;editingClientId=cid;el('clientForm').reset();el('cName').value=c.name||'';el('cDoc').value=c.doc||'';el('cPhone').value=c.phone||'';el('cAddress').value=c.address||'';el('cNotes').value=c.notes||'';el('clientModal').querySelector('.modal-head h3').textContent='Editar cliente';el('saveClientBtn').textContent='Guardar cambios';el('clientModal').showModal()}
function openDebtModal(cid=null){if(!active(state.clients).length)return alert('Primero registrá al menos un cliente.');editingDebtId=null;populateClientSelects();el('debtForm').reset();el('dDate').value=today();if(cid)el('dClient').value=cid;el('debtModal').querySelector('.modal-head h3').textContent='Registrar deuda';el('saveDebtBtn').textContent='Guardar deuda';el('debtModal').showModal()}
function editDebt(did){const d=state.debts.find(x=>x.id===did&&!x.deletedAt);if(!d)return;editingDebtId=did;populateClientSelects();el('debtForm').reset();el('dClient').value=d.clientId;el('dConcept').value=d.concept||'';el('dAmount').value=d.amount||'';el('dDate').value=d.date||today();el('dDue').value=d.due||'';el('debtModal').querySelector('.modal-head h3').textContent='Editar deuda';el('saveDebtBtn').textContent='Guardar cambios';el('debtModal').showModal()}
function openPaymentModal(cid=null){if(!active(state.clients).length)return alert('Primero registrá al menos un cliente.');editingPaymentId=null;populateClientSelects();el('paymentForm').reset();el('pDate').value=today();if(cid)el('pClient').value=cid;el('paymentModal').querySelector('.modal-head h3').textContent='Registrar pago';el('savePaymentBtn').textContent='Guardar pago';el('paymentModal').showModal()}
function editPayment(pid){const p=state.payments.find(x=>x.id===pid&&!x.deletedAt);if(!p)return;editingPaymentId=pid;populateClientSelects();el('paymentForm').reset();el('pClient').value=p.clientId;el('pAmount').value=p.amount||'';el('pDate').value=p.date||today();el('pMethod').value=p.method||'Efectivo';el('pRef').value=p.ref||'';el('paymentModal').querySelector('.modal-head h3').textContent='Editar pago';el('savePaymentBtn').textContent='Guardar cambios';el('paymentModal').showModal()}

function bindForms(){
  el('saveClientBtn').addEventListener('click',e=>{e.preventDefault();const name=el('cName').value.trim();if(!name)return alert('Ingresá el nombre del cliente.');let c=editingClientId?state.clients.find(x=>x.id===editingClientId):null;if(c){Object.assign(c,{name,doc:el('cDoc').value.trim(),phone:el('cPhone').value.trim(),address:el('cAddress').value.trim(),notes:el('cNotes').value.trim()})}else{c={id:id(),name,doc:el('cDoc').value.trim(),phone:el('cPhone').value.trim(),address:el('cAddress').value.trim(),notes:el('cNotes').value.trim(),createdAt:Date.now(),updatedAt:nowIso(),deletedAt:''};state.clients.push(c)}editingClientId=null;saveRecord('clients',c);el('clientModal').close()});
  el('saveDebtBtn').addEventListener('click',e=>{e.preventDefault();const cid=el('dClient').value,amount=Number(el('dAmount').value),concept=el('dConcept').value.trim();if(!cid||!concept||amount<=0)return alert('Completá cliente, concepto y un monto válido.');let d=editingDebtId?state.debts.find(x=>x.id===editingDebtId):null;if(d){Object.assign(d,{clientId:cid,concept,amount,date:el('dDate').value||today(),due:el('dDue').value||''})}else{d={id:id(),clientId:cid,concept,amount,date:el('dDate').value||today(),due:el('dDue').value||'',createdAt:Date.now(),updatedAt:nowIso(),deletedAt:''};state.debts.push(d)}editingDebtId=null;saveRecord('debts',d);el('debtModal').close()});
  el('savePaymentBtn').addEventListener('click',e=>{e.preventDefault();const cid=el('pClient').value,amount=Number(el('pAmount').value);if(!cid||amount<=0)return alert('Completá cliente y un monto válido.');const existing=editingPaymentId?state.payments.find(x=>x.id===editingPaymentId):null;const available=balance(cid)+(existing&&existing.clientId===cid?Number(existing.amount||0):0);if(amount>available)return alert(`El pago no puede superar el saldo disponible de ${money(available)}.`);let p=existing;if(p){Object.assign(p,{clientId:cid,amount,date:el('pDate').value||today(),method:el('pMethod').value,ref:el('pRef').value.trim()})}else{p={id:id(),clientId:cid,amount,date:el('pDate').value||today(),method:el('pMethod').value,ref:el('pRef').value.trim(),createdAt:Date.now(),updatedAt:nowIso(),deletedAt:''};state.payments.push(p)}editingPaymentId=null;saveRecord('payments',p);el('paymentModal').close()});
}

function softDelete(table,record){const stamp=nowIso();record.deletedAt=stamp;record.updatedAt=stamp;queueMutation(table,record.id)}
function deleteDebt(did){const d=state.debts.find(x=>x.id===did&&!x.deletedAt);if(!d)return;const client=clientById(d.clientId)?.name||'este cliente';if(!confirm(`¿Eliminar la deuda “${d.concept}” de ${client} por ${money(d.amount)}?\n\nEl saldo será recalculado. Esta acción quedará registrada para que no reaparezca al sincronizar.`))return;softDelete('debts',d);persistLocal();renderAll();scheduleCloudSync()}
function deletePayment(pid){const p=state.payments.find(x=>x.id===pid&&!x.deletedAt);if(!p)return;const client=clientById(p.clientId)?.name||'este cliente';if(!confirm(`¿Eliminar el pago de ${money(p.amount)} registrado para ${client}?\n\nEl saldo pendiente volverá a aumentar.`))return;softDelete('payments',p);persistLocal();renderAll();scheduleCloudSync()}
function deleteClient(cid){const c=clientById(cid);if(!c)return;const debts=active(state.debts).filter(x=>x.clientId===cid),payments=active(state.payments).filter(x=>x.clientId===cid);const extra=`\n\nTambién se eliminarán ${debts.length} deuda(s) y ${payments.length} pago(s) asociados.`;if(!confirm(`¿Eliminar al cliente “${c.name}”?${extra}\n\nLa eliminación se sincronizará de forma segura.`))return;softDelete('clients',c);debts.forEach(x=>softDelete('debts',x));payments.forEach(x=>softDelete('payments',x));if(currentClientId===cid)currentClientId=null;persistLocal();renderAll();goView('clientes');scheduleCloudSync()}

function localToCloud(table,r){const common={id:r.id,user_id:currentUser.id,workspace_id:workspaceId,created_at:new Date(r.createdAt||Date.now()).toISOString(),updated_at:r.updatedAt||nowIso(),deleted_at:r.deletedAt||null};if(table==='clients')return {...common,name:r.name,doc:r.doc||null,phone:r.phone||null,address:r.address||null,notes:r.notes||null};if(table==='debts')return {...common,client_id:r.clientId,concept:r.concept,amount:Number(r.amount),debt_date:r.date,due_date:r.due||null};return {...common,client_id:r.clientId,amount:Number(r.amount),payment_date:r.date,method:r.method,reference:r.ref||null}}
function cloudToLocal(table,r){if(table==='clients')return {id:r.id,name:r.name||'',doc:r.doc||'',phone:r.phone||'',address:r.address||'',notes:r.notes||'',createdAt:new Date(r.created_at).getTime(),updatedAt:r.updated_at,deletedAt:r.deleted_at||''};if(table==='debts')return {id:r.id,clientId:r.client_id,concept:r.concept||'',amount:Number(r.amount),date:r.debt_date,due:r.due_date||'',createdAt:new Date(r.created_at).getTime(),updatedAt:r.updated_at,deletedAt:r.deleted_at||''};return {id:r.id,clientId:r.client_id,amount:Number(r.amount),date:r.payment_date,method:r.method||'Efectivo',ref:r.reference||'',createdAt:new Date(r.created_at).getTime(),updatedAt:r.updated_at,deletedAt:r.deleted_at||''}}
function stateArray(table){return table==='clients'?state.clients:table==='debts'?state.debts:state.payments}
function mergeRemote(table,rows,full=false){const incoming=(rows||[]).map(r=>cloudToLocal(table,r));if(full){if(table==='clients')state.clients=incoming;if(table==='debts')state.debts=incoming;if(table==='payments')state.payments=incoming;return}const arr=stateArray(table),map=new Map(arr.map(x=>[x.id,x]));for(const r of incoming)map.set(r.id,r);const merged=[...map.values()];if(table==='clients')state.clients=merged;if(table==='debts')state.debts=merged;if(table==='payments')state.payments=merged}

async function pushQueue(){const q=readQueue();if(!q.length)return true;for(const table of ['clients','debts','payments']){const items=q.filter(x=>x.table===table);if(!items.length)continue;const arr=stateArray(table);const rows=items.map(x=>arr.find(r=>r.id===x.id)).filter(Boolean).map(r=>localToCloud(table,r));if(!rows.length){removeQueued(items);continue}const dbTable=table==='clients'?'cecilia_clients':table==='debts'?'cecilia_debts':'cecilia_payments';const {error}=await sb.from(dbTable).upsert(rows,{onConflict:'id'});if(error)throw error;removeQueued(items)}return readQueue().length===0}
async function pullChanges(forceFull=false){let since=forceFull?null:localStorage.getItem(pullKey());const {data,error}=await sb.rpc('cecilia_pull_changes',{p_workspace:workspaceId,p_since:since||null});if(error)throw error;const bundle=data||{};mergeRemote('clients',bundle.clients||[],!since);mergeRemote('debts',bundle.debts||[],!since);mergeRemote('payments',bundle.payments||[],!since);persistLocal();if(bundle.server_time)localStorage.setItem(pullKey(),bundle.server_time);renderAll()}
async function createCloudBackup(force=false){if(!currentUser||!workspaceId||!navigator.onLine||!sb)return;const last=Number(localStorage.getItem(backupKey())||0);if(!force&&Date.now()-last<BACKUP_INTERVAL)return;const snapshot={version:2,workspaceId,clients:state.clients,debts:state.debts,payments:state.payments};const {error}=await sb.from('cecilia_backups').insert({user_id:currentUser.id,workspace_id:workspaceId,snapshot});if(error)throw error;localStorage.setItem(backupKey(),String(Date.now()));const {data}=await sb.from('cecilia_backups').select('id').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).range(20,100);if(data?.length)await sb.from('cecilia_backups').delete().in('id',data.map(x=>x.id))}
async function syncNow(forcePull=false){if(syncing||!currentUser||!workspaceId||!navigator.onLine||!sb)return;syncing=true;lastSyncAttempt=Date.now();updateConnectivityUi();try{const clean=await pushQueue();if(!clean)throw new Error('Quedaron cambios pendientes');const lastPull=localStorage.getItem(pullKey());const stale=!lastPull||Date.now()-new Date(lastPull).getTime()>=PULL_INTERVAL;if(forcePull||stale)await pullChanges(!lastPull);await createCloudBackup(false)}catch(err){console.error('Cecilia sync error',err)}finally{syncing=false;updateConnectivityUi()}}
function scheduleCloudSync(){if(syncTimer)clearTimeout(syncTimer);if(!currentUser||!workspaceId||!navigator.onLine)return;syncTimer=setTimeout(()=>syncNow(false),SYNC_DEBOUNCE)}

async function resolveWorkspace(){
  const cached=(()=>{try{return JSON.parse(localStorage.getItem(WORKSPACE_CACHE_KEY)||'null')}catch{return null}})();
  if(!navigator.onLine&&cached?.userId===currentUser?.id){workspaceId=cached.workspaceId;workspaceRole=cached.role||'user';return true}
  if(!navigator.onLine)return false;
  const {data,error}=await sb.from('cecilia_workspace_members').select('workspace_id,role').eq('user_id',currentUser.id).limit(1).maybeSingle();
  if(error||!data)return false;workspaceId=data.workspace_id;workspaceRole=data.role;localStorage.setItem(WORKSPACE_CACHE_KEY,JSON.stringify({userId:currentUser.id,workspaceId,role:workspaceRole}));return true
}
async function openAuthModal(){if(currentUser&&workspaceId){goView('config');return}if(!navigator.onLine)return alert('Necesitás conexión a internet para iniciar sesión.');if(!sb)return alert('No se pudo cargar el módulo de acceso.');el('authForm').reset();el('authModal').showModal()}
async function signInCloud(){if(!navigator.onLine||!sb)return alert('Necesitás conexión a internet para iniciar sesión.');const email=el('authEmail').value.trim(),password=el('authPassword').value;if(!email||password.length<6)return alert('Ingresá un correo válido y una contraseña de al menos 6 caracteres.');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return alert('No se pudo iniciar sesión: '+error.message);currentUser=data.user;if(!await resolveWorkspace()){await sb.auth.signOut();currentUser=null;workspaceId=null;return alert('Esta cuenta no está autorizada para Cecilia Comercial.')}loadLocal();unlockApp();renderAll();updateAuthUi();el('authModal').close();await syncNow(true)}
async function signUpCloud(){if(!navigator.onLine||!sb)return alert('Necesitás conexión a internet para crear la cuenta.');const email=el('authEmail').value.trim(),password=el('authPassword').value;if(!email||password.length<6)return alert('Ingresá un correo válido y una contraseña de al menos 6 caracteres.');const allowed=await sb.rpc('cecilia_email_is_allowed',{p_email:email});if(allowed.error||allowed.data!==true)return alert('Este correo no está autorizado para crear una cuenta de Cecilia Comercial.');const {data,error}=await sb.auth.signUp({email,password});if(error)return alert('No se pudo crear la cuenta: '+error.message);if(!data.session)return alert('Cuenta creada. Revisá tu correo para confirmar la dirección y luego iniciá sesión.');currentUser=data.user;if(!await resolveWorkspace())return alert('La cuenta fue creada, pero todavía no tiene acceso al espacio de Cecilia.');loadLocal();unlockApp();renderAll();updateAuthUi();el('authModal').close();await syncNow(true)}
async function signOutCloud(){if(!confirm('¿Cerrar sesión en este dispositivo? Los datos sincronizados permanecerán seguros en la nube.'))return;if(sb&&navigator.onLine)await sb.auth.signOut();currentUser=null;workspaceId=null;workspaceRole=null;state=emptyState();currentClientId=null;updateAuthUi();lockApp()}

function exportData(){const blob=new Blob([JSON.stringify({version:2,workspaceId,exportedAt:nowIso(),...state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cecilia-comercial-respaldo-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportExcel(){if(typeof XLSX==='undefined')return alert('El módulo de Excel no está disponible.');const clientes=active(state.clients).map(c=>({Cliente:c.name,'Cédula/RUC':c.doc||'',Teléfono:c.phone||'',Dirección:c.address||'',Observaciones:c.notes||'','Deuda total':totalDebt(c.id),'Total pagado':totalPaid(c.id),'Saldo pendiente':balance(c.id)}));const deudas=active(state.debts).map(d=>({Cliente:clientById(d.clientId)?.name||'',Concepto:d.concept,Fecha:fmtDate(d.date),Vencimiento:d.due?fmtDate(d.due):'',Monto:Number(d.amount),'Saldo pendiente':debtRemaining(d),Estado:debtRemaining(d)<=0?'Pagada':(d.due&&d.due<today()?'Vencida':'Pendiente')}));const pagos=active(state.payments).map(p=>({Fecha:fmtDate(p.date),Cliente:clientById(p.clientId)?.name||'',Monto:Number(p.amount),'Medio de pago':p.method,Referencia:p.ref||''}));const resumen=[{Indicador:'Deuda total registrada',Monto:totalDebt()},{Indicador:'Total cobrado',Monto:totalPaid()},{Indicador:'Saldo pendiente',Monto:balance()},{Indicador:'Cantidad de clientes',Monto:active(state.clients).length}];const wb=XLSX.utils.book_new();const add=(rows,name,widths)=>{const ws=XLSX.utils.json_to_sheet(rows.length?rows:[{'Sin datos':''}]);ws['!cols']=widths.map(w=>({wch:w}));XLSX.utils.book_append_sheet(wb,ws,name)};add(resumen,'Resumen',[28,18]);add(clientes,'Clientes',[28,18,18,30,35,18,18,18]);add(deudas,'Deudas',[28,30,14,14,16,18,14]);add(pagos,'Pagos',[14,28,16,18,24]);XLSX.writeFile(wb,'Cecilia_Comercial_'+today()+'.xlsx')}

function applyReplacementSnapshot(snapshot){const incoming=normalizeState(snapshot);const stamp=nowIso();const incomingIds={clients:new Set(incoming.clients.map(x=>x.id)),debts:new Set(incoming.debts.map(x=>x.id)),payments:new Set(incoming.payments.map(x=>x.id))};for(const table of ['clients','debts','payments']){const existing=stateArray(table);const next=incoming[table];for(const r of existing){if(!incomingIds[table].has(r.id)&&!r.deletedAt){r.deletedAt=stamp;r.updatedAt=stamp;queueMutation(table,r.id)}}for(const r of next){r.deletedAt=r.deletedAt||'';r.updatedAt=stamp;const idx=existing.findIndex(x=>x.id===r.id);if(idx>=0)existing[idx]=r;else existing.push(r);queueMutation(table,r.id)}}persistLocal();renderAll();scheduleCloudSync()}
async function restoreLatestCloudBackup(){if(!currentUser||!workspaceId||!navigator.onLine)return alert('Necesitás conexión para restaurar.');const {data,error}=await sb.from('cecilia_backups').select('snapshot,created_at').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error||!data)return alert('No hay copias disponibles.');if(!confirm(`¿Restaurar la copia del ${new Date(data.created_at).toLocaleString('es-PY')}? Los datos actuales se reemplazarán y el cambio se sincronizará.`))return;await createCloudBackup(true);applyReplacementSnapshot(data.snapshot);await syncNow(true);alert('Copia restaurada correctamente.')}
async function resetData(){if(!active(state.clients).length&&!active(state.debts).length&&!active(state.payments).length)return alert('No hay datos para borrar.');if(!confirm('ATENCIÓN: vas a eliminar todos los clientes, deudas y pagos. Se creará una copia recuperable antes de continuar.'))return;if(prompt('Escribí BORRAR en mayúsculas para continuar.')!=='BORRAR')return alert('Eliminación cancelada.');if(navigator.onLine)try{await createCloudBackup(true)}catch(err){console.error(err);if(!confirm('No se pudo crear la copia en la nube. ¿Continuar de todos modos?'))return}const stamp=nowIso();for(const c of active(state.clients)){c.deletedAt=stamp;c.updatedAt=stamp;queueMutation('clients',c.id)}for(const d of active(state.debts)){d.deletedAt=stamp;d.updatedAt=stamp;queueMutation('debts',d.id)}for(const p of active(state.payments)){p.deletedAt=stamp;p.updatedAt=stamp;queueMutation('payments',p.id)}persistLocal();currentClientId=null;renderAll();goView('dashboard');scheduleCloudSync();alert('Datos marcados como eliminados. La eliminación se sincronizará de forma segura.')}

async function initApp(){
  navSetup();bindForms();
  el('clientSearch')?.addEventListener('input',renderClients);
  el('importFile')?.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data.clients)||!Array.isArray(data.debts)||!Array.isArray(data.payments))throw new Error();if(!confirm(`Importar este respaldo (${data.clients.length} clientes, ${data.debts.length} deudas, ${data.payments.length} pagos) y reemplazar los datos actuales?`))return;applyReplacementSnapshot(data);if(navigator.onLine)await syncNow(true);alert('Respaldo importado correctamente.')}catch{alert('El archivo no es un respaldo válido de Cecilia Comercial.')}finally{e.target.value=''}});
  window.addEventListener('online',()=>{updateConnectivityUi();syncNow(true)});window.addEventListener('offline',updateConnectivityUi);
  window.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&Date.now()-lastSyncAttempt>PULL_INTERVAL)syncNow(true)});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;el('installBtn')?.classList.remove('hidden')});
  el('installBtn')?.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;el('installBtn').classList.add('hidden')});
  if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
  lockApp('Comprobando tu acceso...');
  if(!sb){lockApp('No se pudo cargar el acceso seguro. Verificá la conexión.');return}
  try{const {data}=await sb.auth.getSession();currentUser=data.session?.user||null;if(!currentUser){updateAuthUi();lockApp();return}if(!await resolveWorkspace()){updateAuthUi();lockApp(navigator.onLine?'Esta cuenta no está autorizada para Cecilia Comercial.':'No se pudo verificar el acceso sin conexión. Conectate a Internet una vez.');return}loadLocal();unlockApp();renderAll();updateAuthUi();if(navigator.onLine)await syncNow(true)}catch(err){console.error(err);lockApp('No se pudo verificar el acceso. Intentá nuevamente.')}
  sb.auth.onAuthStateChange((_event,session)=>{if(!session){currentUser=null;workspaceId=null;state=emptyState();lockApp();updateAuthUi()}})
}

document.addEventListener('DOMContentLoaded',initApp);
