const KEY='cecilia_comercial_v1';
const DIRTY_KEY='cecilia_sync_dirty_v1';
const RESET_KEY='cecilia_cloud_reset_v1';
const LAST_USER_KEY='cecilia_last_user_v1';
const LAST_BACKUP_KEY='cecilia_last_backup_v1';
const SUPABASE_URL='https://oxirewjzmnfnbwiugoac.supabase.co';
const SUPABASE_KEY='sb_publishable_gkc-Cjh2ykNYvlf5JRf3NQ_UU2s73jC';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
let state=loadState();
let currentClientId=null;
let deferredPrompt=null;
let currentUser=null;
let syncTimer=null;
let syncing=false;
const el=id=>document.getElementById(id);

function emptyState(){return {clients:[],debts:[],payments:[]}}
function loadState(){try{const raw=localStorage.getItem(KEY);if(!raw)return emptyState();const data=JSON.parse(raw);if(!Array.isArray(data.clients)||!Array.isArray(data.debts)||!Array.isArray(data.payments))throw new Error();return data}catch{return emptyState()}}
function persistLocal(){localStorage.setItem(KEY,JSON.stringify(state))}
function markDirty(){localStorage.setItem(DIRTY_KEY,JSON.stringify({dirty:true,since:Date.now()}));updateConnectivityUi()}
function clearDirty(){localStorage.removeItem(DIRTY_KEY);updateConnectivityUi()}
function isDirty(){return !!localStorage.getItem(DIRTY_KEY)}
function save(){persistLocal();markDirty();renderAll();scheduleCloudSync()}
function id(){if(crypto.randomUUID)return crypto.randomUUID();const a=crypto.getRandomValues(new Uint8Array(16));a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;return [...a].map((b,i)=>([4,6,8,10].includes(i)?'-':'')+b.toString(16).padStart(2,'0')).join('')}
function money(v){return 'Gs. '+Math.round(Number(v)||0).toLocaleString('es-PY')}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function clientById(cid){return state.clients.find(c=>c.id===cid)}
function totalDebt(cid){return state.debts.filter(d=>!cid||d.clientId===cid).reduce((s,d)=>s+Number(d.amount||0),0)}
function totalPaid(cid){return state.payments.filter(p=>!cid||p.clientId===cid).reduce((s,p)=>s+Number(p.amount||0),0)}
function rawBalance(cid){return totalDebt(cid)-totalPaid(cid)}
function balance(cid){return Math.max(0,rawBalance(cid))}
function debtRemaining(debt){const arr=state.debts.filter(d=>d.clientId===debt.clientId).sort((a,b)=>String(a.date).localeCompare(String(b.date))||(a.createdAt||0)-(b.createdAt||0));let paid=totalPaid(debt.clientId);for(const d of arr){const used=Math.min(Number(d.amount||0),Math.max(0,paid));const rem=Number(d.amount||0)-used;paid-=used;if(d.id===debt.id)return Math.max(0,rem)}return Number(debt.amount||0)}
function navSetup(){document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>goView(b.dataset.view)))}
function goView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const t=el(v);if(!t)return;t.classList.add('active');renderAll()}

function renderDashboard(){const ym=today().slice(0,7);const paidMonth=state.payments.filter(p=>String(p.date||'').startsWith(ym)).reduce((s,p)=>s+Number(p.amount||0),0);const overdue=state.debts.filter(d=>d.due&&d.due<today()).reduce((s,d)=>s+debtRemaining(d),0);el('kpiSaldo').textContent=money(balance());el('kpiMes').textContent=money(paidMonth);el('kpiVencida').textContent=money(overdue);el('kpiClientes').textContent=state.clients.filter(c=>balance(c.id)>0).length;const top=[...state.clients].map(c=>({c,b:balance(c.id)})).filter(x=>x.b>0).sort((a,b)=>b.b-a.b).slice(0,5);el('topClientes').innerHTML=top.length?top.map(x=>`<div class="list-row"><span>${esc(x.c.name)}</span><strong>${money(x.b)}</strong></div>`).join(''):'<div class="empty">Sin saldos pendientes.</div>';const last=[...state.payments].sort((a,b)=>String(b.date).localeCompare(String(a.date))||Number(b.createdAt||0)-Number(a.createdAt||0)).slice(0,5);el('ultimosPagos').innerHTML=last.length?last.map(p=>`<div class="list-row"><span>${esc(clientById(p.clientId)?.name||'Cliente')}</span><strong>${money(p.amount)}</strong></div>`).join(''):'<div class="empty">Aún no hay pagos registrados.</div>'}
function renderClients(){const q=(el('clientSearch').value||'').toLowerCase();const arr=state.clients.filter(c=>[c.name,c.doc,c.phone].join(' ').toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name));el('clientsTable').innerHTML=arr.length?arr.map(c=>`<tr><td><button class="client-link" onclick="showClient('${c.id}')">${esc(c.name)}</button></td><td>${esc(c.doc||'-')}</td><td>${esc(c.phone||'-')}</td><td><strong>${money(balance(c.id))}</strong></td><td><button class="btn btn-secondary" onclick="showClient('${c.id}')">Ver cuenta</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty-row">No hay clientes registrados.</td></tr>'}
function renderDebts(){const arr=[...state.debts].sort((a,b)=>String(b.date).localeCompare(String(a.date)));el('debtsTable').innerHTML=arr.length?arr.map(d=>{const rem=debtRemaining(d),overdue=d.due&&d.due<today()&&rem>0;const cls=rem<=0?'ok':overdue?'bad':'warn';const label=rem<=0?'Pagada':overdue?'Vencida':'Pendiente';return `<tr><td>${esc(clientById(d.clientId)?.name||'-')}</td><td>${esc(d.concept)}</td><td>${fmtDate(d.date)}</td><td>${d.due?fmtDate(d.due):'-'}</td><td>${money(d.amount)}</td><td><strong>${money(rem)}</strong></td><td><span class="status ${cls}">${label}</span></td></tr>`}).join(''):'<tr><td colspan="7" class="empty-row">No hay deudas registradas.</td></tr>'}
function renderPayments(){const arr=[...state.payments].sort((a,b)=>String(b.date).localeCompare(String(a.date))||Number(b.createdAt||0)-Number(a.createdAt||0));el('paymentsTable').innerHTML=arr.length?arr.map(p=>`<tr><td>${fmtDate(p.date)}</td><td>${esc(clientById(p.clientId)?.name||'-')}</td><td><strong>${money(p.amount)}</strong></td><td>${esc(p.method)}</td><td>${esc(p.ref||'-')}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-row">No hay pagos registrados.</td></tr>'}
function renderReports(){el('repDeuda').textContent=money(totalDebt());el('repPagado').textContent=money(totalPaid());el('repSaldo').textContent=money(balance());const rows=state.clients.map(c=>({name:c.name,debt:totalDebt(c.id),paid:totalPaid(c.id),bal:balance(c.id)})).sort((a,b)=>b.bal-a.bal);el('reportClientBalances').innerHTML=rows.length?`<div class="table-wrap embedded"><table><thead><tr><th>Cliente</th><th>Deuda</th><th>Pagado</th><th>Saldo</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${money(r.debt)}</td><td>${money(r.paid)}</td><td><strong>${money(r.bal)}</strong></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sin datos para reportar.</div>'}
function populateClientSelects(){const ordered=[...state.clients].sort((a,b)=>a.name.localeCompare(b.name));const opts='<option value="">Seleccionar...</option>'+ordered.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');el('dClient').innerHTML=opts;el('pClient').innerHTML=opts}
function renderClientDetail(){const c=clientById(currentClientId);if(!c)return;el('detailName').textContent=c.name;el('detailMeta').textContent=[c.doc,c.phone,c.address].filter(Boolean).join(' · ');el('detailDebt').textContent=money(totalDebt(c.id));el('detailPaid').textContent=money(totalPaid(c.id));el('detailBalance').textContent=money(balance(c.id));const mov=[...state.debts.filter(d=>d.clientId===c.id).map(d=>({date:d.date,createdAt:d.createdAt||0,type:'Deuda',detail:d.concept,cargo:Number(d.amount),abono:0})),...state.payments.filter(p=>p.clientId===c.id).map(p=>({date:p.date,createdAt:p.createdAt||0,type:'Pago',detail:p.method+(p.ref?' · '+p.ref:''),cargo:0,abono:Number(p.amount)}))].sort((a,b)=>String(a.date).localeCompare(String(b.date))||a.createdAt-b.createdAt);let running=0;el('detailLedger').innerHTML=mov.length?mov.map(m=>{running+=m.cargo-m.abono;return `<tr><td>${fmtDate(m.date)}</td><td>${m.type}</td><td>${esc(m.detail)}</td><td>${m.cargo?money(m.cargo):'-'}</td><td>${m.abono?money(m.abono):'-'}</td><td><strong>${money(Math.max(0,running))}</strong></td></tr>`}).join(''):'<tr><td colspan="6" class="empty-row">Este cliente todavía no tiene movimientos.</td></tr>'}
function showClient(cid){currentClientId=cid;goView('clientDetail')}
function openClientModal(){el('clientForm').reset();el('clientModal').showModal()}
function openDebtModal(cid=null){if(!state.clients.length)return alert('Primero registrá al menos un cliente.');populateClientSelects();el('debtForm').reset();el('dDate').value=today();if(cid)el('dClient').value=cid;el('debtModal').showModal()}
function openPaymentModal(cid=null){if(!state.clients.length)return alert('Primero registrá al menos un cliente.');populateClientSelects();el('paymentForm').reset();el('pDate').value=today();if(cid)el('pClient').value=cid;el('paymentModal').showModal()}
function bindForms(){el('saveClientBtn').addEventListener('click',e=>{e.preventDefault();const name=el('cName').value.trim();if(!name)return alert('Ingresá el nombre del cliente.');state.clients.push({id:id(),name,doc:el('cDoc').value.trim(),phone:el('cPhone').value.trim(),address:el('cAddress').value.trim(),notes:el('cNotes').value.trim(),createdAt:Date.now()});save();el('clientModal').close()});el('saveDebtBtn').addEventListener('click',e=>{e.preventDefault();const cid=el('dClient').value,amount=Number(el('dAmount').value);if(!cid||!el('dConcept').value.trim()||amount<=0)return alert('Completá cliente, concepto y un monto válido.');state.debts.push({id:id(),clientId:cid,concept:el('dConcept').value.trim(),amount,date:el('dDate').value||today(),due:el('dDue').value||'',createdAt:Date.now()});save();el('debtModal').close()});el('savePaymentBtn').addEventListener('click',e=>{e.preventDefault();const cid=el('pClient').value,amount=Number(el('pAmount').value);if(!cid||amount<=0)return alert('Completá cliente y un monto válido.');const saldo=balance(cid);if(saldo<=0)return alert('Este cliente no tiene saldo pendiente.');if(amount>saldo)return alert(`El pago no puede superar el saldo pendiente de ${money(saldo)}.`);state.payments.push({id:id(),clientId:cid,amount,date:el('pDate').value||today(),method:el('pMethod').value,ref:el('pRef').value.trim(),createdAt:Date.now()});save();el('paymentModal').close()})}

function setCloudStatus(status,message){if(el('dataBadge'))el('dataBadge').textContent=status;if(el('sidebarStorage'))el('sidebarStorage').textContent=message;if(el('cloudStatusText'))el('cloudStatusText').textContent=message}
function updateConnectivityUi(){const online=navigator.onLine;if(!online){setCloudStatus(isDirty()?'Offline · pendiente':'Offline','Cecilia funciona sin internet. Los cambios quedan guardados en este dispositivo y se sincronizarán al volver la conexión.');return}if(syncing){setCloudStatus('Sincronizando...','Guardando los cambios locales en la nube.');return}if(currentUser){setCloudStatus(isDirty()?'Pendiente de sincronizar':'Sincronizado',isDirty()?'Hay cambios locales pendientes. Se sincronizarán automáticamente.':`Datos sincronizados con la nube para ${currentUser.email||'tu cuenta'}.`);return}setCloudStatus('Solo copia local','Cecilia funciona offline. Conectá tu cuenta para agregar respaldo y sincronización en la nube.')}
function updateAuthUi(){const signed=!!currentUser;el('cloudBtn').textContent=signed?'Nube conectada':'Conectar nube';el('configCloudBtn').classList.toggle('hidden',signed);el('restoreCloudBtn').classList.toggle('hidden',!signed);el('signOutBtn').classList.toggle('hidden',!signed);updateConnectivityUi()}
function openAuthModal(){if(currentUser){goView('config');return}if(!navigator.onLine)return alert('Para iniciar sesión o crear una cuenta necesitás conexión a internet. Podés seguir usando Cecilia offline mientras tanto.');if(!sb)return alert('No se pudo cargar el módulo de nube. Verificá la conexión e intentá nuevamente.');el('authForm').reset();el('authModal').showModal()}
async function signInCloud(){if(!navigator.onLine||!sb)return alert('Necesitás conexión a internet para iniciar sesión.');const email=el('authEmail').value.trim(),password=el('authPassword').value;if(!email||password.length<6)return alert('Ingresá un correo válido y una contraseña de al menos 6 caracteres.');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return alert('No se pudo iniciar sesión: '+error.message);el('authModal').close();currentUser=data.user;localStorage.setItem(LAST_USER_KEY,currentUser.id);await reconcileWithCloud();updateAuthUi();alert('Cuenta conectada. Cecilia seguirá funcionando aunque pierdas internet.')}
async function signUpCloud(){if(!navigator.onLine||!sb)return alert('Necesitás conexión a internet para crear una cuenta.');const email=el('authEmail').value.trim(),password=el('authPassword').value;if(!email||password.length<6)return alert('Ingresá un correo válido y una contraseña de al menos 6 caracteres.');const {data,error}=await sb.auth.signUp({email,password});if(error)return alert('No se pudo crear la cuenta: '+error.message);if(data.session){currentUser=data.user;localStorage.setItem(LAST_USER_KEY,currentUser.id);el('authModal').close();await reconcileWithCloud();updateAuthUi();alert('Cuenta creada y sincronización activada.')}else alert('Cuenta creada. Revisá tu correo para confirmar la dirección y luego iniciá sesión.')}
async function signOutCloud(){if(!confirm('¿Cerrar la sesión de respaldo en este dispositivo? La copia local seguirá funcionando offline.'))return;if(sb&&navigator.onLine)await sb.auth.signOut();currentUser=null;updateAuthUi()}

function toIso(ms){return new Date(ms||Date.now()).toISOString()}
function cloudRows(){const uid=currentUser.id,now=new Date().toISOString();return {clients:state.clients.map(c=>({id:c.id,user_id:uid,name:c.name,doc:c.doc||null,phone:c.phone||null,address:c.address||null,notes:c.notes||null,created_at:toIso(c.createdAt),updated_at:now})),debts:state.debts.map(d=>({id:d.id,user_id:uid,client_id:d.clientId,concept:d.concept,amount:Number(d.amount),debt_date:d.date,due_date:d.due||null,created_at:toIso(d.createdAt),updated_at:now})),payments:state.payments.map(p=>({id:p.id,user_id:uid,client_id:p.clientId,amount:Number(p.amount),payment_date:p.date,method:p.method,reference:p.ref||null,created_at:toIso(p.createdAt),updated_at:now}))}}
async function fetchCloudState(){const [c,d,p]=await Promise.all([sb.from('cecilia_clients').select('*'),sb.from('cecilia_debts').select('*'),sb.from('cecilia_payments').select('*')]);if(c.error)throw c.error;if(d.error)throw d.error;if(p.error)throw p.error;return {clients:(c.data||[]).map(x=>({id:x.id,name:x.name,doc:x.doc||'',phone:x.phone||'',address:x.address||'',notes:x.notes||'',createdAt:new Date(x.created_at).getTime()})),debts:(d.data||[]).map(x=>({id:x.id,clientId:x.client_id,concept:x.concept,amount:Number(x.amount),date:x.debt_date,due:x.due_date||'',createdAt:new Date(x.created_at).getTime()})),payments:(p.data||[]).map(x=>({id:x.id,clientId:x.client_id,amount:Number(x.amount),date:x.payment_date,method:x.method,ref:x.reference||'',createdAt:new Date(x.created_at).getTime()}))}}
function mergeById(local,cloud){const m=new Map();cloud.forEach(x=>m.set(x.id,x));local.forEach(x=>m.set(x.id,x));return [...m.values()]}
async function upsertCloudState(){const rows=cloudRows();for(const [table,data] of [['cecilia_clients',rows.clients],['cecilia_debts',rows.debts],['cecilia_payments',rows.payments]]){if(!data.length)continue;const {error}=await sb.from(table).upsert(data,{onConflict:'id'});if(error)throw error}}
async function deleteCloudState(){for(const table of ['cecilia_payments','cecilia_debts','cecilia_clients']){const {error}=await sb.from(table).delete().eq('user_id',currentUser.id);if(error)throw error}}
async function createCloudBackup(force=false){if(!currentUser||!navigator.onLine||!sb)return;const last=Number(localStorage.getItem(LAST_BACKUP_KEY)||0);if(!force&&Date.now()-last<5*60*1000)return;const {error}=await sb.from('cecilia_backups').insert({user_id:currentUser.id,snapshot:state});if(!error){localStorage.setItem(LAST_BACKUP_KEY,String(Date.now()));const {data}=await sb.from('cecilia_backups').select('id').order('created_at',{ascending:false}).range(30,200);if(data?.length)await sb.from('cecilia_backups').delete().in('id',data.map(x=>x.id))}}
async function applyPendingReset(){const pending=localStorage.getItem(RESET_KEY);if(!pending||pending!==currentUser.id)return false;await createCloudBackup(true);await deleteCloudState();localStorage.removeItem(RESET_KEY);clearDirty();return true}
async function syncNow(){if(syncing||!currentUser||!navigator.onLine||!sb)return;syncing=true;updateConnectivityUi();try{if(await applyPendingReset()){persistLocal();renderAll();return}const cloud=await fetchCloudState();state={clients:mergeById(state.clients,cloud.clients),debts:mergeById(state.debts,cloud.debts),payments:mergeById(state.payments,cloud.payments)};persistLocal();await upsertCloudState();await createCloudBackup();clearDirty();renderAll()}catch(err){console.error('Sync error',err);markDirty()}finally{syncing=false;updateConnectivityUi()}}
function scheduleCloudSync(){if(syncTimer)clearTimeout(syncTimer);if(!currentUser||!navigator.onLine)return;syncTimer=setTimeout(syncNow,700)}
async function reconcileWithCloud(){markDirty();await syncNow()}
async function restoreLatestCloudBackup(){if(!currentUser||!navigator.onLine||!sb)return alert('Necesitás conexión a internet para restaurar una copia de la nube.');const {data,error}=await sb.from('cecilia_backups').select('*').order('created_at',{ascending:false}).limit(1);if(error||!data?.length)return alert('No hay copias disponibles en la nube.');if(!confirm('¿Restaurar la última copia de la nube? Los datos locales actuales serán reemplazados.'))return;const snap=data[0].snapshot;if(!snap||!Array.isArray(snap.clients)||!Array.isArray(snap.debts)||!Array.isArray(snap.payments))return alert('La copia no tiene un formato válido.');state=snap;persistLocal();markDirty();renderAll();await syncNow();alert('Copia restaurada correctamente.')}
async function initCloud(){updateConnectivityUi();if(!sb){updateAuthUi();return}try{const {data}=await sb.auth.getSession();currentUser=data.session?.user||null;if(currentUser){localStorage.setItem(LAST_USER_KEY,currentUser.id);updateAuthUi();if(navigator.onLine)await syncNow()}else updateAuthUi();sb.auth.onAuthStateChange((_event,session)=>{currentUser=session?.user||null;if(currentUser){localStorage.setItem(LAST_USER_KEY,currentUser.id);scheduleCloudSync()}updateAuthUi()})}catch{updateAuthUi()}}

function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cecilia-comercial-respaldo-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportExcel(){if(typeof XLSX==='undefined')return alert('El módulo de Excel no está disponible sin conexión. Podés usar el respaldo JSON offline y exportar Excel cuando vuelva internet.');const clientes=state.clients.map(c=>({Cliente:c.name,'Cédula/RUC':c.doc||'',Teléfono:c.phone||'',Dirección:c.address||'',Observaciones:c.notes||'','Deuda total':totalDebt(c.id),'Total pagado':totalPaid(c.id),'Saldo pendiente':balance(c.id)}));const deudas=state.debts.map(d=>({Cliente:clientById(d.clientId)?.name||'',Concepto:d.concept,Fecha:fmtDate(d.date),Vencimiento:d.due?fmtDate(d.due):'',Monto:Number(d.amount),'Saldo pendiente':debtRemaining(d),Estado:debtRemaining(d)<=0?'Pagada':(d.due&&d.due<today()?'Vencida':'Pendiente')}));const pagos=state.payments.map(p=>({Fecha:fmtDate(p.date),Cliente:clientById(p.clientId)?.name||'',Monto:Number(p.amount),'Medio de pago':p.method,Referencia:p.ref||''}));const resumen=[{Indicador:'Deuda total registrada',Monto:totalDebt()},{Indicador:'Total cobrado',Monto:totalPaid()},{Indicador:'Saldo pendiente',Monto:balance()},{Indicador:'Cantidad de clientes',Monto:state.clients.length}];const wb=XLSX.utils.book_new();const add=(rows,name,widths)=>{const ws=XLSX.utils.json_to_sheet(rows.length?rows:[{'Sin datos':''}]);ws['!cols']=widths.map(w=>({wch:w}));XLSX.utils.book_append_sheet(wb,ws,name)};add(resumen,'Resumen',[28,18]);add(clientes,'Clientes',[28,18,18,30,35,18,18,18]);add(deudas,'Deudas',[28,30,14,14,16,18,14]);add(pagos,'Pagos',[14,28,16,18,24]);XLSX.writeFile(wb,'Cecilia_Comercial_'+today()+'.xlsx')}
async function resetData(){if(!state.clients.length&&!state.debts.length&&!state.payments.length)return alert('No hay datos para borrar.');if(!confirm('ATENCIÓN: vas a eliminar TODOS los clientes, deudas y pagos. Antes de continuar, recomendamos exportar un respaldo. ¿Continuar?'))return;if(prompt('Escribí BORRAR en mayúsculas para continuar.')!=='BORRAR')return alert('Eliminación cancelada.');if(!confirm('Última confirmación: ¿borrar definitivamente?'))return;const uid=currentUser?.id||localStorage.getItem(LAST_USER_KEY);if(uid)localStorage.setItem(RESET_KEY,uid);state=emptyState();currentClientId=null;persistLocal();markDirty();renderAll();if(currentUser&&navigator.onLine)await syncNow();goView('dashboard');alert(navigator.onLine&&currentUser?'Datos eliminados. Se guardó una copia recuperable en la nube.':'Datos locales eliminados. Si existe una cuenta conectada, la eliminación se sincronizará cuando vuelva internet.')}
function fmtDate(s){if(!s)return'-';const [y,m,d]=String(s).split('-');return y&&m&&d?`${d}/${m}/${y}`:s}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderAll(){renderDashboard();renderClients();renderDebts();renderPayments();renderReports();populateClientSelects();if(el('clientDetail').classList.contains('active'))renderClientDetail();updateConnectivityUi()}

el('clientSearch').addEventListener('input',renderClients);
el('importFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data.clients)||!Array.isArray(data.debts)||!Array.isArray(data.payments))throw new Error();if(!confirm(`Se reemplazarán los datos actuales por el respaldo seleccionado (${data.clients.length} clientes, ${data.debts.length} deudas, ${data.payments.length} pagos). ¿Continuar?`))return;state=data;persistLocal();markDirty();renderAll();scheduleCloudSync();alert('Respaldo importado correctamente.')}catch{alert('El archivo no es un respaldo válido de Cecilia Comercial.')}finally{e.target.value=''}});
window.addEventListener('online',()=>{updateConnectivityUi();syncNow()});
window.addEventListener('offline',updateConnectivityUi);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;el('installBtn').classList.remove('hidden')});
el('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;el('installBtn').classList.add('hidden')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
navSetup();bindForms();renderAll();initCloud();