const CC_DELETE_QUEUE_KEY='cecilia_delete_queue_v1';
let ccEditingClientId=null;
let ccEditingDebtId=null;
let ccEditingPaymentId=null;

function ccDeleteQueue(){try{return JSON.parse(localStorage.getItem(CC_DELETE_QUEUE_KEY)||'[]')}catch{return []}}
function ccQueueDelete(table,recordId){const q=ccDeleteQueue();if(!q.some(x=>x.table===table&&x.id===recordId)){q.push({table,id:recordId});localStorage.setItem(CC_DELETE_QUEUE_KEY,JSON.stringify(q))}}
async function ccFlushDeleteQueue(){if(!currentUser||!navigator.onLine||!sb)return;const q=ccDeleteQueue();if(!q.length)return;const pending=[];for(const item of q){try{const {error}=await sb.from(item.table).delete().eq('id',item.id).eq('user_id',currentUser.id);if(error)throw error}catch(err){console.error('Delete sync error',err);pending.push(item)}}if(pending.length)localStorage.setItem(CC_DELETE_QUEUE_KEY,JSON.stringify(pending));else localStorage.removeItem(CC_DELETE_QUEUE_KEY)}

const ccOriginalSyncNow=syncNow;
syncNow=async function(){await ccFlushDeleteQueue();return ccOriginalSyncNow()};

function ccSetModalMode(kind,isEdit){const map={client:{modal:'clientModal',title:'Nuevo cliente',editTitle:'Editar cliente',button:'saveClientBtn',save:'Guardar cliente',editSave:'Guardar cambios'},debt:{modal:'debtModal',title:'Registrar deuda',editTitle:'Editar deuda',button:'saveDebtBtn',save:'Guardar deuda',editSave:'Guardar cambios'},payment:{modal:'paymentModal',title:'Registrar pago',editTitle:'Editar pago',button:'savePaymentBtn',save:'Guardar pago',editSave:'Guardar cambios'}};const cfg=map[kind];const modal=el(cfg.modal);const h=modal?.querySelector('.modal-head h3');const b=el(cfg.button);if(h)h.textContent=isEdit?cfg.editTitle:cfg.title;if(b)b.textContent=isEdit?cfg.editSave:cfg.save}

const ccOriginalOpenClientModal=openClientModal;
openClientModal=function(){ccEditingClientId=null;ccSetModalMode('client',false);return ccOriginalOpenClientModal()};
const ccOriginalOpenDebtModal=openDebtModal;
openDebtModal=function(cid=null){ccEditingDebtId=null;ccSetModalMode('debt',false);return ccOriginalOpenDebtModal(cid)};
const ccOriginalOpenPaymentModal=openPaymentModal;
openPaymentModal=function(cid=null){ccEditingPaymentId=null;ccSetModalMode('payment',false);return ccOriginalOpenPaymentModal(cid)};

function editClient(cid){const c=clientById(cid);if(!c)return;ccEditingClientId=cid;ccSetModalMode('client',true);el('clientForm').reset();el('cName').value=c.name||'';el('cDoc').value=c.doc||'';el('cPhone').value=c.phone||'';el('cAddress').value=c.address||'';el('cNotes').value=c.notes||'';el('clientModal').showModal()}
function editDebt(did){const d=state.debts.find(x=>x.id===did);if(!d)return;ccEditingDebtId=did;ccSetModalMode('debt',true);populateClientSelects();el('debtForm').reset();el('dClient').value=d.clientId;el('dConcept').value=d.concept||'';el('dAmount').value=d.amount||'';el('dDate').value=d.date||today();el('dDue').value=d.due||'';el('debtModal').showModal()}
function editPayment(pid){const p=state.payments.find(x=>x.id===pid);if(!p)return;ccEditingPaymentId=pid;ccSetModalMode('payment',true);populateClientSelects();el('paymentForm').reset();el('pClient').value=p.clientId;el('pAmount').value=p.amount||'';el('pDate').value=p.date||today();el('pMethod').value=p.method||'Efectivo';el('pRef').value=p.ref||'';el('paymentModal').showModal()}

el('saveClientBtn').addEventListener('click',e=>{if(!ccEditingClientId)return;e.preventDefault();e.stopImmediatePropagation();const c=clientById(ccEditingClientId);const name=el('cName').value.trim();if(!c||!name)return alert('Ingresá el nombre del cliente.');Object.assign(c,{name,doc:el('cDoc').value.trim(),phone:el('cPhone').value.trim(),address:el('cAddress').value.trim(),notes:el('cNotes').value.trim()});ccEditingClientId=null;save();el('clientModal').close()},true);
el('saveDebtBtn').addEventListener('click',e=>{if(!ccEditingDebtId)return;e.preventDefault();e.stopImmediatePropagation();const d=state.debts.find(x=>x.id===ccEditingDebtId);const cid=el('dClient').value,amount=Number(el('dAmount').value);if(!d||!cid||!el('dConcept').value.trim()||amount<=0)return alert('Completá cliente, concepto y un monto válido.');Object.assign(d,{clientId:cid,concept:el('dConcept').value.trim(),amount,date:el('dDate').value||today(),due:el('dDue').value||''});ccEditingDebtId=null;save();el('debtModal').close()},true);
el('savePaymentBtn').addEventListener('click',e=>{if(!ccEditingPaymentId)return;e.preventDefault();e.stopImmediatePropagation();const p=state.payments.find(x=>x.id===ccEditingPaymentId);const cid=el('pClient').value,amount=Number(el('pAmount').value);if(!p||!cid||amount<=0)return alert('Completá cliente y un monto válido.');const available=balance(cid)+(p.clientId===cid?Number(p.amount||0):0);if(amount>available)return alert(`El pago no puede superar el saldo disponible de ${money(available)}.`);Object.assign(p,{clientId:cid,amount,date:el('pDate').value||today(),method:el('pMethod').value,ref:el('pRef').value.trim()});ccEditingPaymentId=null;save();el('paymentModal').close()},true);

function deleteClient(cid){const c=clientById(cid);if(!c)return;const debts=state.debts.filter(x=>x.clientId===cid),payments=state.payments.filter(x=>x.clientId===cid);const extra=debts.length||payments.length?`\n\nTambién se eliminarán ${debts.length} deuda(s) y ${payments.length} pago(s) asociados.`:'';if(!confirm(`¿Eliminar al cliente “${c.name}”?${extra}\n\nEsta acción no se puede deshacer.`))return;debts.forEach(x=>ccQueueDelete('cecilia_debts',x.id));payments.forEach(x=>ccQueueDelete('cecilia_payments',x.id));ccQueueDelete('cecilia_clients',cid);state.debts=state.debts.filter(x=>x.clientId!==cid);state.payments=state.payments.filter(x=>x.clientId!==cid);state.clients=state.clients.filter(x=>x.id!==cid);if(currentClientId===cid)currentClientId=null;save();if(!currentClientId)goView('clientes')}
function deleteDebt(did){const d=state.debts.find(x=>x.id===did);if(!d)return;const client=clientById(d.clientId)?.name||'este cliente';if(!confirm(`¿Eliminar la deuda “${d.concept}” de ${client} por ${money(d.amount)}?\n\nEl saldo del cliente será recalculado. Esta acción no se puede deshacer.`))return;ccQueueDelete('cecilia_debts',did);state.debts=state.debts.filter(x=>x.id!==did);save()}
function deletePayment(pid){const p=state.payments.find(x=>x.id===pid);if(!p)return;const client=clientById(p.clientId)?.name||'este cliente';if(!confirm(`¿Eliminar el pago de ${money(p.amount)} registrado para ${client}?\n\nEl saldo pendiente volverá a aumentar. Esta acción no se puede deshacer.`))return;ccQueueDelete('cecilia_payments',pid);state.payments=state.payments.filter(x=>x.id!==pid);save()}

renderClients=function(){const q=(el('clientSearch').value||'').toLowerCase();const arr=state.clients.filter(c=>[c.name,c.doc,c.phone].join(' ').toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name));el('clientsTable').innerHTML=arr.length?arr.map(c=>`<tr><td><button class="client-link" onclick="showClient('${c.id}')">${esc(c.name)}</button></td><td>${esc(c.doc||'-')}</td><td>${esc(c.phone||'-')}</td><td><strong>${money(balance(c.id))}</strong></td><td><div class="row-actions"><button class="btn btn-secondary btn-small" onclick="showClient('${c.id}')">Ver</button><button class="btn btn-secondary btn-small" onclick="editClient('${c.id}')">Editar</button><button class="btn btn-danger btn-small" onclick="deleteClient('${c.id}')">Eliminar</button></div></td></tr>`).join(''):'<tr><td colspan="5" class="empty-row">No hay clientes registrados.</td></tr>'};
renderDebts=function(){const arr=[...state.debts].sort((a,b)=>String(b.date).localeCompare(String(a.date)));el('debtsTable').innerHTML=arr.length?arr.map(d=>{const rem=debtRemaining(d),overdue=d.due&&d.due<today()&&rem>0;const cls=rem<=0?'ok':overdue?'bad':'warn';const label=rem<=0?'Pagada':overdue?'Vencida':'Pendiente';return `<tr><td>${esc(clientById(d.clientId)?.name||'-')}</td><td>${esc(d.concept)}</td><td>${fmtDate(d.date)}</td><td>${d.due?fmtDate(d.due):'-'}</td><td>${money(d.amount)}</td><td><strong>${money(rem)}</strong></td><td><span class="status ${cls}">${label}</span></td><td><div class="row-actions"><button class="btn btn-secondary btn-small" onclick="editDebt('${d.id}')">Editar</button><button class="btn btn-danger btn-small" onclick="deleteDebt('${d.id}')">Eliminar</button></div></td></tr>`}).join(''):'<tr><td colspan="8" class="empty-row">No hay deudas registradas.</td></tr>'};
renderPayments=function(){const arr=[...state.payments].sort((a,b)=>String(b.date).localeCompare(String(a.date))||Number(b.createdAt||0)-Number(a.createdAt||0));el('paymentsTable').innerHTML=arr.length?arr.map(p=>`<tr><td>${fmtDate(p.date)}</td><td>${esc(clientById(p.clientId)?.name||'-')}</td><td><strong>${money(p.amount)}</strong></td><td>${esc(p.method)}</td><td>${esc(p.ref||'-')}</td><td><div class="row-actions"><button class="btn btn-secondary btn-small" onclick="editPayment('${p.id}')">Editar</button><button class="btn btn-danger btn-small" onclick="deletePayment('${p.id}')">Eliminar</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="empty-row">No hay pagos registrados.</td></tr>'};

renderAll();